framework:
    security_headers:
        headers:
            content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'"
            x_frame_options: "DENY"
            x_content_type_options: "nosniff"
            x_xss_protection: "1; mode=block"
            referrer_policy: "strict-origin-when-cross-origin"
            permissions_policy: "geolocation=(), microphone=()"
            strict_transport_security: "max-age=31536000; includeSubDomains"
            
        # Configuration spécifique pour les environnements de développement
        env:
            dev:
                headers:
                    content_security_policy: "default-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:*; script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:*; style-src 'self' 'unsafe-inline' http://localhost:*; img-src 'self' data: http://localhost:*; font-src 'self' http://localhost:*; connect-src 'self' http://localhost:*"
                    strict_transport_security: null
