version: '3.8'

services:
  app:
    image: node:16
    container_name: green-clean-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db
      - php
      - redis

  db:
    image: mysql:8
    container_name: green-clean-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: green_clean
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:8.1-apache
    container_name: green-clean-php
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mailer:
    image: axllent/mailpit
    container_name: mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data:
networks:
  default:
    driver: bridge
