version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: prod
    container_name: symfony_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./var/prod:/var/www/var
    environment:
      - APP_ENV=prod
      - DATABASE_URL=PROD_DATABASE_URL
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PROD_ROOT_PASSWORD
      MYSQL_DATABASE: green
      MYSQL_USER: symfony
      MYSQL_PASSWORD: PROD_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: symfony_redis
    restart: always

volumes:
  mysql_data:
