
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /etc/ssl/certs:/etc/ssl/certs:ro # Monte les certificats SSL
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:root@db:3306/green
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017/green_clean
    depends_on:
      - db
      - redis
      - mongo

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: always
    ports:
      - "8000:80"
      - "443:443" # Ajout du port HTTPS
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/ssl # Dossier pour les certificats SSL
    depends_on:
      - app

  db:
    image: mysql:8.2
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: green
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: symfony_redis
    restart: always
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  mailer:
    image: axllent/mailpit
    container_name: symfony_mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mongo:
    image: mongo:6
    container_name: symfony_mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: green_clean
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: symfony_mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  node:
    image: node:18
    container_name: symfony_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
  mongo_data:
networks:
  default:
    driver: bridge
