

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://symfony:symfony@db:3306/green
      MONGODB_URL: mongodb://admin:admin@mongo:27017
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - mongo
      - redis

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: always
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: green
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: symfony_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: green_clean
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: symfony_mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: symfony_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  mongo_data:
