controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
reset_password:
    path: /reset-password
    controller: Symfony\Bundle\SecurityBundle\Controller\ForgottenPasswordController::requestTokenAction

admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

admin_donations:
    path: /admin/donations
    controller: App\Controller\Admin\DonationsController::index

admin_users:
    path: /admin/users
    controller: App\Controller\Admin\UsersController::index

admin_users_edit:
    path: /admin/users/{id}/edit
    controller: App\Controller\Admin\UsersController::edit
    methods: [GET, POST]

admin_users_delete:
    path: /admin/users/{id}/delete
    controller: App\Controller\Admin\UsersController::delete
    methods: [POST]

admin_users_create:
    path: /admin/users/create
    controller: App\Controller\Admin\UsersController::create
    methods: [GET, POST]

admin_projects:
    path: /admin/projects
    controller: App\Controller\Admin\ProjectsController::index

admin_projects_edit:
    path: /admin/projects/{id}/edit
    controller: App\Controller\Admin\ProjectController::edit
    methods: [GET, POST]

admin_projects_create:
    path: /admin/projects/create
    controller: App\Controller\Admin\ProjectController::create
    methods: [GET, POST]
admin_projects_delete:
    path: /admin/projects/{id}/delete
    controller: App\Controller\Admin\ProjectController::delete
    methods: [GET, POST]

user_dashboard:
    path: /user/dashboard
    controller: App\Controller\UserController::dashboard

user_profile:
    path: /user/profile
    controller: App\Controller\UserController::profile

user_projects:
    path: /user/projects
    controller: App\Controller\UserController::projects

user_donations:
    path: /user/donations
    controller: App\Controller\UserController::donations

user_settings:
    path: /user/settings
    controller: App\Controller\UserController::settings
